version: "3"
services:
  webserver3:
    container_name: ConM21AIE245_3
    image: httpd:latest
    volumes:
      - "./webserver3:/usr/local/apache2/htdocs"
    ports:
      - 3000:80
  webserver1:
    container_name: ConM21AIE245_1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./api:/var/www/html/"
    ports:
      - 5000:80
  database:
    container_name: ConM21AIE245_2
    image: mysql:latest
    environment:
      MYSQL_DATABASE: m21aie245_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    depends_on:
      - database